/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartpharma;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

public class Client extends javax.swing.JFrame {
String database = "jdbc:sqlite:C:\\Users\\kouraichi\\Documents\\GitHub\\SmartPharma\\pharmacy.sqlite";
    ResultSet rs = null;
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        table();
    }
    
      private void table(){
    
    try{
         Class.forName("org.sqlite.JDBC");
         Connection conn = DriverManager.getConnection(database);
        String sql = "select IDClient, CIN , Nom_Client as 'Nom ', Prenom_Client as 'Prenom',Adresse_Client as 'Adresse', Tel_Client as 'Telephone', Credit , Mutuelle  from Client";
        PreparedStatement pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
       
    }
    catch(ClassNotFoundException | SQLException ex){
       JOptionPane.showMessageDialog(null, ex);
        
    }
    
       
    
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gesion de Client");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Zud Juice", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Num Client");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 110, 120, 40));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 115, 253, 32));

        jLabel2.setFont(new java.awt.Font("Zud Juice", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 32));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 230, 32));

        jLabel3.setFont(new java.awt.Font("Zud Juice", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRENOM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 93, 32));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 230, 32));

        jLabel4.setFont(new java.awt.Font("Zud Juice", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("    CIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 93, 32));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 230, 32));

        jLabel5.setFont(new java.awt.Font("Zud Juice", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mutuelle");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 100, 32));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 230, 32));

        jLabel6.setFont(new java.awt.Font("Zud Juice", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adresse");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 80, 32));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 230, 32));

        jButton1.setFont(new java.awt.Font("Vijaya", 0, 22)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/search-icon.png"))); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jButton4.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/remove_from_database_256.png"))); // NOI18N
        jButton4.setText("Supprimer");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 162, 50));

        jButton5.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/folder-invoices-icon.png"))); // NOI18N
        jButton5.setText("Modifier");
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 170, 50));

        jButton6.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/save.png"))); // NOI18N
        jButton6.setText("Enregistrer");
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 173, 50));

        jTable1.setFont(new java.awt.Font("Chaparral Pro Light", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        jTable1.setRowHeight(26);
        jTable1.setRowMargin(3);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 760, 170));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 230, 32));

        jLabel7.setFont(new java.awt.Font("Zud Juice", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Credit");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 93, 32));

        jLabel9.setFont(new java.awt.Font("Zud Juice", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tel");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 73, 32));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Benificier", "Non Benificier" }));
        jComboBox1.setOpaque(false);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 120, 30));

        jButton7.setFont(new java.awt.Font("Vijaya", 0, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/add-icon.png"))); // NOI18N
        jButton7.setText("Nouveau");
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 173, 50));

        jLabel10.setFont(new java.awt.Font("Dancing in the Rainbow", 0, 80)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gestion de Clients");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 390, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 780, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Backgroun5.jpg"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(1280, 500));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      Statement stmt=null;
        String name = jTextField2.getText();
        String Cprenom = jTextField3.getText();
        String cinn = jTextField4.getText();
        String tel = jTextField5.getText();
        String Addres = jTextField6.getText();
        String cre = jTextField7.getText();
        String Mutue = (String)jComboBox1.getSelectedItem();
        
        try{
            Class.forName("org.sqlite.JDBC");
                Connection conn = DriverManager.getConnection(database);
                    stmt =(Statement) conn.createStatement();
             String sql = " insert into Client (CIN,Nom_Client,Prenom_Client,Adresse_Client,Tel_Client,Credit,Mutuelle) values('"+cinn+"','"+name+"','"+Cprenom+"','"+Addres+"','"+tel+"','"+cre+"','"+Mutue+"')";        
                    
             stmt.executeUpdate(sql);
             JOptionPane.showMessageDialog(null, "le nouveau Client ajouter ");
             
             jTextField1.setText("");
             jTextField2.setText("");
             jTextField3.setText("");
             jTextField4.setText("");
             jTextField5.setText("");
             jTextField6.setText("");
             jTextField7.setText("");
             
               rs.close();
                    conn.close();
                    
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            
        }
        table();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        try{
             Class.forName("org.sqlite.JDBC");
         Connection conn = DriverManager.getConnection(database);
         int row = jTable1.getSelectedRow();
         String Table_click = (jTable1.getModel().getValueAt(row,0).toString());
            String sql = "select * from Client where IDClient = '"+Table_click+"'";
           PreparedStatement pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next()){
             String add = rs.getString("IDClient");
               jTextField1.setText(add);
               String add1 = rs.getString("Nom_Client");
               jTextField2.setText(add1);
                 String add2 = rs.getString("Prenom_Client");
               jTextField3.setText(add2);
               String add3 = rs.getString("Adresse_Client");
               jTextField6.setText(add3);
               String add4 = rs.getString("Tel_Client");
               jTextField5.setText(add4);
               String add5 = rs.getString("Credit");
               jTextField7.setText(add5);
               String add6 = rs.getString("CIN");
               jTextField4.setText(add6);
               String add7 = rs.getString("Mutuelle");
               jComboBox1.setSelectedItem(add7);
               rs.close();
           conn.close();
           }
        }catch(ClassNotFoundException | SQLException e){
            
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        try{
             Class.forName("org.sqlite.JDBC");
        Connection conn=DriverManager.getConnection(database);
        String ID = jTextField1.getText();
     String name = jTextField2.getText();
        String Cprenom = jTextField3.getText();
        String cinn = jTextField4.getText();
        String tel = jTextField5.getText();
        String Addres = jTextField6.getText();
        String cre = jTextField7.getText();
        String Mutue = (String)jComboBox1.getSelectedItem();
 
        String sql = "update Client set Nom_Client = '"+name+"', Prenom_Client = '"+Cprenom+"' , CIN = '"+cinn+"', Adresse_Client = '"+Addres+"', Tel_Client = '"+tel+"', Credit = '"+cre+"' , Mutuelle = '"+Mutue+"' where IDClient = '"+ID+"' "; 
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, " Client Modifie ");
        }catch(ClassNotFoundException | SQLException e){
            
        }
        table();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String sql1="delete from Client where IDClient='"+jTextField1.getText()+"'";
        String str=null;
        Statement stmt=null;
        ResultSet rs=null;
        try{
            Class.forName("org.sqlite.JDBC");
        Connection conn=DriverManager.getConnection(database);
        stmt =(Statement) conn.createStatement();
        stmt.executeUpdate(sql1);
        
        JOptionPane.showMessageDialog(null,"   Client Supprimé  ");  
        }catch(Exception e){
            
        }
        table();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
                
        DefaultTableModel d=(DefaultTableModel) jTable1.getModel();
        
        int rows=d.getRowCount();
if(rows>0)  {
    for(int i=0;i<rows;i++)
d.removeRow(0);

}
String id=  jTextField1.getText();
Statement stmt=null;
        ResultSet rs=null;
        if (id.equals(""))
               { JOptionPane.showMessageDialog(this,"SVP entrer Le Numero de Client !");
               table();
            }else{
        
        
        try{
             Class.forName("org.sqlite.JDBC");
    Connection conn=DriverManager.getConnection(database);
            stmt =(Statement) conn.createStatement();
            String sql="select IDClient , Nom_Client,Prenom_Client,CIN , Adresse_Client , Tel_Client,Credit,Mutuelle from Client where IDClient = '"+id+"'   ";
            rs=stmt.executeQuery(sql);
            String iddd = jTextField1.getText();
             if(iddd!=null){
            while(rs.next()){
                String idd = jTextField1.getText();
                       
                       String cinn = rs.getString("CIN");
                       String name= rs.getString("Nom_Client");
                       String Cprenom= rs.getString("Prenom_Client");
                       String Addres= rs.getString("Adresse_Client");
                       String tel= rs.getString("Tel_Client");                            
                       String cre= rs.getString("Credit");
                       String Mutue= rs.getString("Mutuelle");
        
       d.addRow(new Object[]{idd,cinn,name,Cprenom,Addres,tel,cre,Mutue});
            }
            
           rs.close();
           conn.close(); 
             }else{
                                 JOptionPane.showMessageDialog(null, "Client n'existe pas ! ");
                              table();
                            jTextField2.setText("");
                                    }
        }catch(Exception e){
            
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       jTextField1.setText("");
             jTextField2.setText("");
             jTextField3.setText("");
             jTextField4.setText("");
             jTextField5.setText("");
             jTextField6.setText("");
             jTextField7.setText("");
             table();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
