/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartpharma;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class EHome extends javax.swing.JFrame {

    String database = "jdbc:sqlite:C:\\Users\\kouraichi\\Documents\\GitHub\\SmartPharma\\pharmacy.sqlite";
    String id_transfer;
 ResultSet rs = null;
 
    /**
     * Creates new form Home
     */
    public EHome(String ID) {
        this.setResizable(false);
        this.setUndecorated(true);
        this.setVisible(true);
        id_transfer = ID;
        initComponents();
        Toolkit tk1 = Toolkit.getDefaultToolkit();
        int xsize = (int) tk1.getScreenSize().getWidth();
        int ysize = (int) tk1.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        jLabel10.setVisible(false);
        jTextField1.setVisible(false);
    }

    public EHome() {
        /*  this.setResizable(false);
         this.setUndecorated(true);*/
        this.setVisible(true);

        initComponents();
        Toolkit tk1 = Toolkit.getDefaultToolkit();
        int xsize = (int) tk1.getScreenSize().getWidth();
        int ysize = (int) tk1.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        jTextField1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savebtn = new javax.swing.JButton();
        LabelQty = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LabelDate = new javax.swing.JTextField();
        TextQty2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        ButtonCalculate = new javax.swing.JButton();
        ButtonAdd = new javax.swing.JButton();
        TextAmt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Bill_no = new javax.swing.JTextField();
        LabelWelcome1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        TextAmount = new javax.swing.JTextField();
        TextDiscount = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        LabelWelcome2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        savebtn.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        savebtn.setForeground(new java.awt.Color(0, 51, 204));
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/report.png"))); // NOI18N
        savebtn.setText("Valider & Génerer Facture");
        savebtn.setOpaque(false);
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 280, 50));

        LabelQty.setEditable(false);
        LabelQty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(LabelQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 40, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField3.setNextFocusableComponent(LabelQty);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, 50, 30));

        jLabel16.setFont(new java.awt.Font("Chaparral Pro Light", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TVA");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 30, 20));

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setMaximumRowCount(20);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBox1.setNextFocusableComponent(LabelQty);
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 370, 30));

        jButton6.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 204));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Client-icon.png"))); // NOI18N
        jButton6.setText("Client");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 260, 60));

        jButton5.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/refresh.png"))); // NOI18N
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 17, 60, 50));

        jButton4.setFont(new java.awt.Font("Chaparral Pro Light", 0, 21)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/report.png"))); // NOI18N
        jButton4.setText("Consultation des recettes");
        jButton4.setEnabled(false);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, 60));

        jButton3.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/exp.png"))); // NOI18N
        jButton3.setText("Consulter la Date d'expiration");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 290, 60));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/add items.png"))); // NOI18N
        jButton1.setText("Gestion de Medicaments");
        jButton1.setEnabled(false);
        jButton1.setName(""); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 250, 60));

        jButton2.setFont(new java.awt.Font("Chaparral Pro Light", 0, 22)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/stock.png"))); // NOI18N
        jButton2.setText("Stock Medicaments");
        jButton2.setOpaque(false);
        jButton2.setVerifyInputWhenFocusTarget(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 250, 60));

        LabelDate.setEditable(false);
        LabelDate.setNextFocusableComponent(LabelQty);
        getContentPane().add(LabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 120, 120, 30));

        TextQty2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TextQty2.setNextFocusableComponent(LabelQty);
        TextQty2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextQty2FocusLost(evt);
            }
        });
        TextQty2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextQty2KeyPressed(evt);
            }
        });
        getContentPane().add(TextQty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 60, 30));

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField6.setNextFocusableComponent(LabelQty);
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 200, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField4.setNextFocusableComponent(LabelQty);
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 100, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2.setNextFocusableComponent(LabelQty);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 80, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 204));
        jLabel3.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 100, 40, 20));

        jLabel4.setFont(new java.awt.Font("Zekton ExHv", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Entrer le Nom de medicament :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 270, 20));

        jLabel6.setFont(new java.awt.Font("Chaparral Pro Light", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Qty");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 30, 20));

        jLabel5.setFont(new java.awt.Font("Chaparral Pro Light", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Disp");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 40, 20));

        jLabel7.setFont(new java.awt.Font("Chaparral Pro Light", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date Expiration");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, 20));

        jLabel8.setFont(new java.awt.Font("Chaparral Pro Light", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Code Famille");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 90, 20));

        jLabel9.setFont(new java.awt.Font("Chaparral Pro Light", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Prix");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 40, 20));

        jButton8.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 51, 204));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Client-icon.png"))); // NOI18N
        jButton8.setText("Fournisseur");
        jButton8.setEnabled(false);
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 250, 60));

        ButtonCalculate.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        ButtonCalculate.setForeground(new java.awt.Color(0, 51, 204));
        ButtonCalculate.setText("Calculer Total");
        ButtonCalculate.setOpaque(false);
        ButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 670, 140, 30));

        ButtonAdd.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        ButtonAdd.setForeground(new java.awt.Color(0, 51, 204));
        ButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/add items.png"))); // NOI18N
        ButtonAdd.setText("Ajouter");
        ButtonAdd.setOpaque(false);
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 190, 150, 50));

        TextAmt.setBackground(new java.awt.Color(255, 255, 0));
        TextAmt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TextAmt.setNextFocusableComponent(LabelQty);
        getContentPane().add(TextAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 100, 30));

        jLabel11.setFont(new java.awt.Font("Zekton ExHv", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Numero de Client");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 150, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 204));
        jLabel12.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bill No");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 100, 50, 20));

        Bill_no.setEditable(false);
        Bill_no.setNextFocusableComponent(LabelQty);
        getContentPane().add(Bill_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 120, 60, 30));

        LabelWelcome1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        LabelWelcome1.setForeground(new java.awt.Color(255, 255, 255));
        LabelWelcome1.setText("Bienvenue : ");
        getContentPane().add(LabelWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        jLabel13.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("%");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 630, 30, 30));

        LabelTotal.setEditable(false);
        getContentPane().add(LabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 670, 90, 30));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Vijaya", 1, 20)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Reduction :");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 630, -1, -1));

        TextAmount.setEditable(false);
        getContentPane().add(TextAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 590, 90, 30));

        TextDiscount.setEditable(false);
        TextDiscount.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(TextDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, 50, 30));

        jLabel14.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Montant (Total):");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 590, 140, 30));

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField7.setNextFocusableComponent(LabelQty);
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 100, 30));

        jLabel15.setFont(new java.awt.Font("Chaparral Pro Light", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Montant( détail)");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 110, 20));

        LabelWelcome2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        LabelWelcome2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabelWelcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 50, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 162, 10, 120));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 280, 1250, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1280, 10));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 162, 10, 120));

        jButton9.setFont(new java.awt.Font("Chaparral Pro Light", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 51, 204));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/famille_Medicament.png"))); // NOI18N
        jButton9.setText("Famille Medicament");
        jButton9.setEnabled(false);
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 260, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero Client", "N° Medicament", "Nom de Medicament", "Famille Medicament", "Date d'expiration", "Quantité", "Prix Vente", "TVA", "Montant(Total)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setRowHeight(28);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 51));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 1070, 270);

        jButton7.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 51, 204));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Clean.png"))); // NOI18N
        jButton7.setText("Reset");
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(1090, 90, 140, 40);

        jButton12.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 51, 204));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/delete small.png"))); // NOI18N
        jButton12.setText("Supprimer");
        jButton12.setOpaque(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(1090, 140, 140, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1250, 290));

        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/background 7.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 40, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 470, 80, 30));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(107, 25));

        jMenu1.setText("Fichier ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/cropped-Graphic-Lock.png"))); // NOI18N
        jMenuItem1.setText("Deconnexion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/exit.png"))); // NOI18N
        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Editer");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem6.setText("Creer utilisateur");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem7.setText("Changer mot de passe");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jMenuItem8.setText("Supprimer utilisateur");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Outils  ");

        jMenuItem9.setText("Calculatrice");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Aide");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jMenuItem3.setText("Afficher l'aide");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("A propos de Projet");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu4.setText(" ? ");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jMenuItem5.setText("Mettre a jour");
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EGestion_Medicament adm = new EGestion_Medicament();
        adm.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Gestion_stock gst = new Gestion_stock();
       gst.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        Expiration_Date exd = new Expiration_Date();
        exd.setVisible(true);
                
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        EHome m = new EHome();

        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        EClient cl = new EClient();
        cl.setVisible(true);
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
     
          jTextField4.setText("");
                TextAmt.setText("0");
         
                TextQty2.setText("");
           jTextField6.setText("");
            jTextField2.setText("");
               jTextField7.setText("");
               jComboBox1.setSelectedItem("");
                TextQty2.setText("");
             jButton12.setText("Supprimer");
            jTextField3.setText("");
            jTextField6.setText("");
                LabelQty.setText("");   
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        
        Fournisseur fr = new Fournisseur();
        fr.setVisible(true);
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void ButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalculateActionPerformed
if(jCheckBox1.isSelected()){
        Double  total=0.0; 
         Double amount=Double.parseDouble(TextAmount.getText());
     Double  discount=Double.parseDouble(TextDiscount.getText());
     Double dis=discount/100*amount;
        total=amount-dis;
          DecimalFormat df = new DecimalFormat("##.##");
df.setRoundingMode(RoundingMode.DOWN);
LabelTotal.setText(df.format(total));
}
else{
    
}

    }//GEN-LAST:event_ButtonCalculateActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        Double qty = Double.parseDouble(TextQty2.getText());
        Double qtyav = Double.parseDouble(LabelQty.getText());
        Double amount = Double.parseDouble(TextAmt.getText());
       
        if (qty > qtyav) {
            JOptionPane.showMessageDialog(this, "quantité dépassés, veuillez saisir moins ");
        } else {
            String idme = jTextField1.getText();
            String idc = jTextField6.getText();
            String name = (String) jComboBox1.getSelectedItem();
            String ppv = jTextField2.getText();
            String exp = jTextField4.getText();
            String date = LabelDate.getText();
            String batch = jTextField7.getText();
            String tva = jTextField3.getText();

            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            int rows = d.getRowCount();
            int qtyint = qty.intValue();

            d.addRow(new Object[]{idc ,idme, name, batch, exp, qtyint, ppv,tva, amount});

            TextQty2.setText("");
            qtyav = qtyav - qty;
            DecimalFormat df = new DecimalFormat("##");
            df.setRoundingMode(RoundingMode.DOWN);
            LabelQty.setText(df.format(qtyav));
            int i = 0;
            Double total = 0.0;
            while (i <= rows) {

                String amt = (d.getValueAt(i, 8).toString());
                Double amounta = Double.parseDouble(amt);

                total = total + amounta;
//  Double amount2a=Double.parseDouble(jTextField14.getText());    

                //jLabel35.setText("Rs. "+total);
                DecimalFormat dft = new DecimalFormat("##.##");
                dft.setRoundingMode(RoundingMode.DOWN);
                TextAmount.setText(dft.format(total));

                LabelTotal.setText(dft.format(total));
                i++;
            }

        }
        ButtonCalculate.doClick();
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
jButton7.doClick();
        DefaultTableModel d=(DefaultTableModel) jTable1.getModel();
int row_click=Integer.parseInt(jLabel10.getText());
int rows=d.getRowCount();    
  d.removeRow(row_click);
  ////////////////////////
   
TextAmount.setText("");
LabelTotal.setText("");
jCheckBox1.setSelected(false);
if(jCheckBox1.isSelected()){

    TextDiscount.setEditable(true);
     TextDiscount.setBackground(Color.yellow);
     ButtonCalculate.doClick();
}
else{
      TextDiscount.setEditable(false);
       TextDiscount.setBackground(Color.white);
       TextDiscount.setText(""+0);
       ButtonCalculate.doClick();
    }

int i=0;
    
Double  total=0.0; 
int j=0;
while(i<=rows){
        
         String amt=(d.getValueAt(i,5).toString());   
        Double amounta=Double.parseDouble(amt);
        

 total=total+amounta;
//  Double amount2a=Double.parseDouble(jTextField14.getText());    
   
    
 //jLabel35.setText("Rs. "+total);
   DecimalFormat dft = new DecimalFormat("##.##");
dft.setRoundingMode(RoundingMode.DOWN);
TextAmount.setText(dft.format(total));
LabelTotal.setText(dft.format(total));
i++;
 
        
 }      
        
        
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //jComboBox1.removeAllItems();

        try {
            Class.forName("org.sqlite.JDBC");
            Connection connn = DriverManager.getConnection(database);
            Statement stmte = connn.createStatement();
            Statement stmt = connn.createStatement();
            AutoCompleteDecorator.decorate(jComboBox1);

            ResultSet rs = stmte.executeQuery("select DISTINCT  UPPER(Nom_M) from Medicament order by Nom_M asc");
            ResultSet rs1 = stmt.executeQuery("select utilisateur from Login ");
            jComboBox1.setSelectedItem("");
            while (rs.next()) {

                jComboBox1.addItem((String) rs.getObject(1));

                //  LabelWelcome2.setText(rs.getString("utilisateur"));
            }

          LabelWelcome2.setText(rs1.getString("utilisateur"));

            rs.close();
           rs1.close();
            connn.close();
            stmte.close();
           stmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       // jComboBox1.removeAllItems();
        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection(database);
            Statement stmt = conn.createStatement();
            String b = "select max(IDFacture)as IDFacture from Facture";

            ResultSet rs = stmt.executeQuery(b);
            if (rs.next()) {
                int billno = rs.getInt("IDFacture");
                int billnodisplay = billno + 1;
                Bill_no.setText("" + billnodisplay);

            }
            rs.close();
            conn.close();
            stmt.close();

        } catch (Exception e) {

        }

        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection(database);

            Statement stmt = conn.createStatement();
            String b = "select date() as date";
            ResultSet rs = stmt.executeQuery(b);
            if (rs.next()) {
                String c = rs.getString("date");
                LabelDate.setText(c);

            }
            rs.close();
            conn.close();
            stmt.close();

        } catch (Exception e1) {

        }
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();

        int rows = d.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                d.removeRow(0);
            }
        }
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible

        String tmp = (String) jComboBox1.getSelectedItem();

        String sql = "select * from Medicament where Nom_M like '" + tmp + "' ;";
       // String sql1 = "select nom_FamilleMedicament from famille_Medicament where IDFamille = (select IdFamille from Medicament where Nom_M = '" + tmp + "')";

        try {
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection(database);
            Statement stmt = conn.createStatement();
           // Statement stmte = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            //ResultSet rs1 = stmte.executeQuery(sql1);
            if (rs.next()) {
                String add = rs.getString("IDMedicament");
                jTextField1.setText(add);
                String add1 = rs.getString("Date_expiration");
                jTextField4.setText(add1);
                String add2 = rs.getString("IDFamille");
                jTextField7.setText(add2);
                String add3 = rs.getString("Prix");
                jTextField2.setText(add3);
                String add4 = rs.getString("Quantite_stock");
                LabelQty.setText(add4);
                String add5 = rs.getString("TVA");
                jTextField3.setText(add5);

            }
            rs.close();
           // rs1.close();
            conn.close();
            stmt.close();
           // stmte.close();
        } catch (ClassNotFoundException | SQLException e) {

        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void TextQty2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextQty2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {//if we press enter, it execute code
            double qtyav1 = Double.parseDouble(LabelQty.getText());
            int qty1 = Integer.parseInt(TextQty2.getText());
            double mrp = Double.parseDouble(jTextField2.getText());
            double amt = qty1 * mrp;

            DecimalFormat df = new DecimalFormat("##.##");
            df.setRoundingMode(RoundingMode.DOWN);
            TextAmt.setText(df.format(amt));
            ButtonAdd.doClick();
        }

    }//GEN-LAST:event_TextQty2KeyPressed

    private void TextQty2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextQty2FocusLost

        int qty1 = Integer.parseInt(TextQty2.getText());
        double mrp = Double.parseDouble(jTextField2.getText());
        double amt = qty1 * mrp;

        DecimalFormat df = new DecimalFormat("##.##");
        df.setRoundingMode(RoundingMode.DOWN);
        TextAmt.setText(df.format(amt));

    }//GEN-LAST:event_TextQty2FocusLost

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(jCheckBox1.isSelected()){

    TextDiscount.setEditable(true);
     TextDiscount.setBackground(Color.yellow);
     ButtonCalculate.doClick();
}
else{
      TextDiscount.setEditable(false);
       TextDiscount.setBackground(new Color(204, 204 ,204));
       TextDiscount.setText(""+0);
       ButtonCalculate.doClick();
    }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int  row =jTable1.getSelectedRow();
     String Table_click=(jTable1.getModel().getValueAt(row,0).toString());
     int row_num=(jTable1.getSelectedRow());
            
             
  
      // jButton12.setText("Supprimer "+Table_click);
      jLabel10.setText(""+row_num);       
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        
        String b_id=Bill_no.getText();
//String username=LabelWelcome.getText();
         String  str=null;
        Statement stmt=null;
        Statement stmt1=null;
        ResultSet rs=null;
  try{
      
     
        try{
             Class.forName("org.sqlite.JDBC");
    Connection conn=DriverManager.getConnection(database);
    DefaultTableModel d=(DefaultTableModel) jTable1.getModel();
 
String idm=(d.getValueAt(0,0).toString());
String totalamt=LabelTotal.getText();
       String disc=TextDiscount.getText();
           String amtbeforedisc=TextAmount.getText();
           String date=LabelDate.getText();
           int rows=d.getRowCount(); 

               String sql="insert into Facture(IDFacture,IDClient,Date_Facture,Total_PPV,reduction,total_avreduction)values (?,?,?,?,?,?)";
               
    PreparedStatement pst = conn.prepareStatement(sql);
            
    pst.setString(1,b_id);
    pst.setString(2, idm);
    pst.setString(3, date);
    pst.setString(4, amtbeforedisc);
    pst.setString(5, disc);
    pst.setString(6, totalamt);
    pst.execute();
   
    int i=0;
    while(i<=rows){
        String idmm = (jTable1.getModel().getValueAt(i, 1).toString());
            String name=(jTable1.getModel().getValueAt(i,2).toString());
            
            String idFamille=(jTable1.getModel().getValueAt(i,3).toString());
               String exp=(jTable1.getModel().getValueAt(i,4).toString());  
                 String qty=(jTable1.getModel().getValueAt(i,5).toString());  
                  String ppv=(jTable1.getModel().getValueAt(i,6).toString());
                  String tvaa=(jTable1.getModel().getValueAt(i,7).toString());
                  String amtt = (jTable1.getModel().getValueAt(i,8).toString());
      String sql1="insert into Ligne_Commande(IDFacture,IDMedicament,Quantite_V,Nom_V,Prix_V,TVA,Date_ex,Montant_t) values(?,?,?,?,?,?,?,?)";

            pst = conn.prepareStatement(sql1);
     pst.setString(1,b_id);
    pst.setString(2, idmm);
    pst.setString(3, qty);
    pst.setString(4, name);
    pst.setString(5, ppv);
    pst.setString(6, tvaa);
    pst.setString(7, exp);
    pst.setString(8, amtt);   
    pst.execute();
   
    String sql2="update Medicament set Quantite_stock=Quantite_Stock-'"+qty+"' where Nom_M like  '"+name+"'  ";
              pst = conn.prepareStatement(sql2);  
              pst.execute();
             i++ ;
            }
             
stmt.close();
conn.close();
        }catch(Exception e){
        }
                 finally{
              
                JOptionPane.showMessageDialog(null,"Facture Enregistrer clic OK pour l'imprimer ");
                Facture fm = new Facture(b_id);
                fm.setVisible(true);
        } 
        
       }catch(Exception e)   {
           
       }
  
    }//GEN-LAST:event_savebtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Login L = new Login();
        L.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       
        Creation_utilisateur cu = new Creation_utilisateur();
        cu.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        
        Changer_Mdp cm = new Changer_Mdp();
        cm.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
     
        Supprimer_utilisateur su = new Supprimer_utilisateur();
        su.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        Famille_Medicament fm = new Famille_Medicament();
        fm.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Calculatrice cl = new Calculatrice();
        cl.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         propos_application prp = new propos_application();
        prp.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bill_no;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonCalculate;
    private javax.swing.JTextField LabelDate;
    private javax.swing.JTextField LabelQty;
    private javax.swing.JTextField LabelTotal;
    private javax.swing.JLabel LabelWelcome1;
    private javax.swing.JLabel LabelWelcome2;
    private javax.swing.JTextField TextAmount;
    private javax.swing.JTextField TextAmt;
    private javax.swing.JTextField TextDiscount;
    private javax.swing.JTextField TextQty2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
