/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartpharma;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Expiration_Date extends javax.swing.JFrame {
 String database="jdbc:sqlite:C:\\Users\\kouraichi\\Documents\\GitHub\\SmartPharma\\pharmacy.sqlite";

    /**
     * Creates new form G_stock
     */
    public Expiration_Date() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(200, 10));
        setPreferredSize(new java.awt.Dimension(870, 728));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Clean.png"))); // NOI18N
        jButton3.setText("Effacer");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 631, 130, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom Medicament", "Quantite Disponible", "Code Famille Medicament", "Prix de Vente(PPV)", "Date Expiration"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 840, 390));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Chaparral Pro Light", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/ok.png"))); // NOI18N
        jButton1.setText("Verifier");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(550, 20, 170, 50);

        jLabel3.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Entrer la Date d'expiration");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 30, 210, 30);

        jComboBox2.setMaximumRowCount(12);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox2.setOpaque(false);
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(290, 30, 120, 30);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2017", "2018", "2019", "2020", "2021", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "" }));
        jComboBox4.setOpaque(false);
        jPanel2.add(jComboBox4);
        jComboBox4.setBounds(440, 30, 60, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 800, 80));

        jButton4.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/back-icon.png"))); // NOI18N
        jButton4.setText("Quitter");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 630, -1, 50));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 870, 10));

        jLabel10.setFont(new java.awt.Font("Dancing in the Rainbow", 0, 70)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Consultation La Date d'expiration");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 660, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Backgroun5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    DefaultTableModel d=(DefaultTableModel) jTable1.getModel();

int rows=d.getRowCount();
if(rows>0)  {
    for(int i=0;i<rows;i++)
d.removeRow(0);
}
//d.addRow(new Object[]{" ","  "," "," ","  "," "});

      String monthstr=(String) jComboBox2.getSelectedItem();
      String year=(String) jComboBox4.getSelectedItem();
              String str=null;
        Statement stmt1=null;
        ResultSet rs1=null;
int month = 0;
int date=1;
if(monthstr=="January")
           month=1;
        else
           if(monthstr=="February")
          month=2;
        else
                 if(monthstr=="March")
          month=3;
        else
                       if(monthstr=="April")
          month=4;
        else
                             if(monthstr=="May")
          month=5;
        else
                                   if(monthstr=="June")
          month=6;
        else
                                         if(monthstr=="July")
          month=7;
        else
                                              if(monthstr=="August")
          month=8;
        else
                                                   if(monthstr=="September")
          month=9;
        else
                                                         if(monthstr=="October")
          month=10;
        else
                                                               if(monthstr=="November")
          month=11;
        else
                                                                     if(monthstr=="December")
          month=12;
   try{
        Class.forName("org.sqlite.JDBC");
    Connection conn=DriverManager.getConnection(database);
            stmt1 =(Statement) conn.createStatement();
            String sql1="select Nom_M,Quantite_stock,IdFamille,Prix,Date_expiration from Medicament where Date_expiration <=  '"+year+"/"+month+"/"+date+"'order by Nom_M asc;  ";
            rs1=stmt1.executeQuery(sql1);
            while(rs1.next()){
                   String ss=rs1.getString("Nom_M");
            String name=ss.toUpperCase();
            String qty= rs1.getString("Quantite_stock");
            String idf= rs1.getString("IdFamille");
            String mrp= rs1.getString("Prix");

            String exp= rs1.getString("Date_expiration");


        d.addRow(new Object[]{name,qty,idf,mrp,exp});
            }
            
             rs1.close();
            conn.close();
            
   }catch(Exception e){
       JOptionPane.showMessageDialog(this,e.getMessage());
   }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
         DefaultTableModel d=(DefaultTableModel) jTable1.getModel();
         
         int rows=d.getRowCount();
if(rows>0)  {
    for(int i=0;i<rows;i++)
d.removeRow(0);}
jComboBox4.setSelectedItem("2017");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
         String str=null;
        Statement stmt=null;
        ResultSet rs=null;
String month = null;
  String year = null;
  

        try{
           Class.forName("org.sqlite.JDBC");
    Connection conn=DriverManager.getConnection(database);
            stmt =(Statement) conn.createStatement();
            String sql="select monthname(curdate()) as 'month',  year(curdate()) as 'year';";
            rs=stmt.executeQuery(sql);
            rs.next();
            {   month= rs.getString("month");
              
             year= rs.getString("year");
            
              
                jComboBox2.setSelectedItem(month);
                     jComboBox4.setSelectedItem(year);
        
                   
                }
            
      
        }catch (Exception e) {
        
        }   
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expiration_Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expiration_Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expiration_Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expiration_Date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expiration_Date().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
