/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartpharma;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Gestion_stock extends javax.swing.JFrame {
 String database="jdbc:sqlite:C:\\Users\\kouraichi\\Documents\\GitHub\\SmartPharma\\pharmacy.sqlite";

    /**
     * Creates new form G_stock
     */
    public Gestion_stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock Médicament ");
        setLocation(new java.awt.Point(200, 0));
        setPreferredSize(new java.awt.Dimension(844, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setOpaque(false);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nom Medicament", "Quantite Disponible", "Code Famille Medicament", "Prix de Vente(PPV)", "Date Expiration"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 0));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 810, 390));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(160, 12, 155, 35);

        jLabel2.setFont(new java.awt.Font("Chaparral Pro Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ou clique ici pour ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(390, 30, 170, 30);

        jButton1.setFont(new java.awt.Font("Chaparral Pro Light", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/stock.png"))); // NOI18N
        jButton1.setText("Afficher tout");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(570, 21, 200, 50);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/search-icon.png"))); // NOI18N
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(330, 10, 50, 40);

        jLabel3.setFont(new java.awt.Font("Chaparral Pro Light", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom Medicament");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 150, 40);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(160, 64, 155, 35);

        jButton5.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 204));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/search-icon.png"))); // NOI18N
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(330, 62, 50, 40);

        jLabel5.setFont(new java.awt.Font("Chaparral Pro Light", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Code Famille");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 60, 120, 38);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 800, 110));

        jButton4.setFont(new java.awt.Font("Chaparral Pro Light", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/back-icon.png"))); // NOI18N
        jButton4.setText("Quitter");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 630, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 870, 10));

        jLabel10.setFont(new java.awt.Font("Dancing in the Rainbow", 0, 80)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Stock Medicament");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 440, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Backgroun5.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
                                
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
jButton2.doClick();


}
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DefaultTableModel d=(DefaultTableModel) jTable1.getModel();
       
        int rows=d.getRowCount();
if(rows>0)  {
    for(int i=0;i<rows;i++)
d.removeRow(0);
}
        
 String name1=jTextField1.getText();
              String str=null;
        Statement stmt1=null;
        ResultSet rs1=null;
        
         if (name1.equals(""))
               { JOptionPane.showMessageDialog(this,"Entrer Le nom de Medicament");

            }else{
                try{
                     Class.forName("org.sqlite.JDBC");
    Connection conn=DriverManager.getConnection(database);
            stmt1 =(Statement) conn.createStatement();
            
            String sql1 = "select Nom_M , Quantite_stock , IdFamille , Prix , Date_expiration from Medicament where Nom_M like '%"+name1+"%' order by Nom_M asc;";
            rs1=stmt1.executeQuery(sql1);
            
            while(rs1.next()){
                String ss=rs1.getString("Nom_M");
            String name=ss.toUpperCase();
            String qty= rs1.getString("Quantite_stock");
            String idf= rs1.getString("IdFamille");
            String mrp= rs1.getString("Prix");

            String exp= rs1.getString("Date_expiration");


        d.addRow(new Object[]{name,qty,idf,mrp,exp});
            }
            
            rs1.close();
            conn.close();
                }catch(Exception e){
                    
                }
             
         }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        DefaultTableModel d=(DefaultTableModel) jTable1.getModel();

int rows=d.getRowCount();
if(rows>0)  {
    for(int i=0;i<rows;i++)
d.removeRow(0);
}
            String name1=jTextField1.getText();
              String str=null;
        Statement stmt1=null;
        ResultSet rs1=null;
         try{
         Class.forName("org.sqlite.JDBC");
    Connection conn=DriverManager.getConnection(database);
            stmt1 =(Statement) conn.createStatement();
            String sql1="select Nom_M , Quantite_stock , IdFamille , Prix , Date_expiration from Medicament order by Nom_M asc;   ";
            rs1=stmt1.executeQuery(sql1);
            while(rs1.next()){
                String ss=rs1.getString("Nom_M");
            String name=ss.toUpperCase();
            String qty= rs1.getString("Quantite_stock");
            String idf= rs1.getString("IdFamille");
            String mrp= rs1.getString("Prix");

            

            String exp= rs1.getString("Date_expiration");


        d.addRow(new Object[]{name,qty,idf,mrp,exp});
            }
            
              rs1.close();
            conn.close();
         }catch(Exception e){
             
         }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       DefaultTableModel d=(DefaultTableModel) jTable1.getModel();
       
        int rows=d.getRowCount();
if(rows>0)  {
    for(int i=0;i<rows;i++)
d.removeRow(0);
}
String name1=jTextField3.getText();
              String str=null;
        Statement stmt1=null;
        ResultSet rs1=null;
        if (name1.equals(""))
               { JOptionPane.showMessageDialog(this,"Entrer Le nom de Medicament");

            }else{
        try{
             Class.forName("org.sqlite.JDBC");
    Connection conn=DriverManager.getConnection(database);
            stmt1 =(Statement) conn.createStatement();
            String sql = "select Nom_M , Quantite_stock , IdFamille , Prix , Date_expiration from Medicament where IdFamille = "+name1+" order by IdFamille asc ;";
            rs1=stmt1.executeQuery(sql);
            
            while(rs1.next()){
                String ss=rs1.getString("Nom_M");
            String name=ss.toUpperCase();
            String qty= rs1.getString("Quantite_stock");
            String idf= rs1.getString("IdFamille");
            String mrp= rs1.getString("Prix");

            String exp= rs1.getString("Date_expiration");


        d.addRow(new Object[]{name,qty,idf,mrp,exp});
            }
            
            rs1.close();
            conn.close();
        }catch(Exception e){
            
            
        }
        }   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
